#include "/Engine/Private/Common.ush"

//--------------------------------------------------------------------------------------
// Structs
//--------------------------------------------------------------------------------------

struct FAgent
{
	float3 position;
};

//--------------------------------------------------------------------------------------
// Buffers
//--------------------------------------------------------------------------------------

RWStructuredBuffer<FAgent> agents;
RWStructuredBuffer<float3> positions;
RWStructuredBuffer<float> times;

[numthreads(256, 1, 1)]
void MainComputeShader(uint3 ThreadId : SV_DispatchThreadID)
{
    int index = ThreadId.x;

    FAgent agent = agents[index];
    
	agent.position.z = sin(times[index]) * 20; 
    times[index] += 0.016f;

	agents[index] = agent;
}