#include "/Engine/Public/Platform.ush"

//--------------------------------------------------------------------------------------
// Buffers
//--------------------------------------------------------------------------------------

RWTexture2D<float4> TextureToClear;

//--------------------------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------------------------

int Width;
int Height;

[numthreads(16,16,1)]
void ClearTexture (uint3 id : SV_DispatchThreadID)
{
	if (id.x < 0 || id.x >= (uint)Width || id.y < 0 || id.y >= (uint)Height) {
		return;
	}
	
	TextureToClear[id.xy] = 0;
}