#include "/Engine/Public/Platform.ush"

//--------------------------------------------------------------------------------------
// Structs
//--------------------------------------------------------------------------------------

struct SpeciesSetting {
	float move_speed;
	float turn_speed;

	float sensor_angle_degrees;
	float sensor_offset_distance;
	int sensor_size;
	float4 color;
};

//--------------------------------------------------------------------------------------
// Buffers
//--------------------------------------------------------------------------------------

RWStructuredBuffer<SpeciesSetting> SpeciesSettings : register(u0);
RWTexture2D<float4> TrailMap : register(u1);
RWTexture2D<float4> ColorMap : register(u2);

//--------------------------------------------------------------------------------------
// Variables
//--------------------------------------------------------------------------------------

uint NumSpecies;
int Width;
int Height;

[numthreads(8,8,1)]
void UpdateColorMap (uint3 id : SV_DispatchThreadID)
{
	if (id.x < 0 || id.x >= (uint)3840 || id.y < 0 || id.y >= (uint)2160) {
		return;
	}

	const float4 map = TrailMap[id.xy];

	float4 color = 0;
	for (uint i = 0; i < NumSpecies; i ++) {
		const float4 mask = float4(i==0, i==1, i==2,i==3);
		color += SpeciesSettings[i].color * dot(map, mask); 
	}
	
	ColorMap[id.xy] = color;
}